### PR TITLE
Check for equipped might set items by comparing item names

### PR DESCRIPTION
**Pull request by Masgalor**
Final improvement to detect the actual block value.

Im not sure if you will like it, the code structure is not that nice.
However, it is at least a working example.

### CODE REVIEW

**Comment by getov** [comment]
Hmmm, no I will have to do it in a different way. People already reported lag spikes for the previous version so I moved the calculations on mouse over. 
There are too many nested "for" loops which I have to avoid because it's getting computationally heavy.

**Comment by Masgalor** [comment]
You could insert the following line of code into your master branch it will stop scanning the tooltip after a blank line occurs. A blank line indicates that we reached the section of the tooltip containing set information, there is nothing interesting to be found.

https://github.com/getov/CharacterStatsClassic/pull/28/files#diff-fe2f5a75f1638e381dde45cba60a32b3R763

**Comment by Masgalor** [comment]
Maybe we could do the following to improve this.

That "for loop" is only necessary to resolve all the item names.
We could do this when the addon is loaded, since the locales cant change ingame anyway, and write all names in one long string.

So we could use "string.match" to check if the equipped items appear in our list.

What do you think?

**Comment by getov** [comment]
People are reporting that every piece of Might gear also adds the set bonus. I cannot test if this happens when they've unlocked the set bonus or it happens even if you have 2 pieces.
This bug is present with the changes in pull request #24 - Check for multiple block value effects.

**Comment by getov** [comment]
Anyways, I should have fixed the problem with the latest release.

**Pull request closed without merging**
