### PR TITLE
Check for multiple block value effects

### PR DESCRIPTION
**Pull request by Masgalor**
Extends the existing function to find and add up multiple sources of block values if present.

### CODE REVIEW

**Comment by Masgalor** [comment]
This will only work for additional values on the shield.
Maybe we should loop through more item slots?

There is at least one trinket in bwl that also increases the block value.
[Styleens impending scarab](https://classic.wowhead.com/item=19431/styleens-impeding-scarab)

**Comment by Masgalor** [comment]
We still fail to discover values added by set bonuses.

(Fortunately) there is only one set in the game that has a block value bonus.
[Battlegear of Might](https://classic.wowhead.com/item-set=209/battlegear-of-might)

**Comment by getov** [comment]
For the Warrior's Might set we have to manually detect if the player has the set bonus and add that. It's kinda "boring" work to do. But I think it should be doable.

**Comment by getov** [comment]
It might be a bit heavy on the computational part but it should be fine since it's done only when the player hovers on the stat.

**Comment by getov** [comment]
If it gets heavy on the performance, the calculation can be moved and executed only when the player hovers on the stat.

**Pull request merged**
