### PR TITLE
Fix for Warrior's defense

### PR DESCRIPTION
**Pull request by Ardash**

### CODE REVIEW

**Comment by Ardash** [comment]
There is same problem like in previous version.

**Comment by getov** [comment]
This is really weird. Can you insert a 
print(defense);
print(GetTalentInfo(3, 2));

In ClassUtils.lua -> CSC_GetWarriorDefenseFromTalents() just before "return defense", on line 92.
And show me what it prints.

**Comment by Ardash** [comment]
10
Предчувствие 136056 1 3 5 5 nil 1

Предчувствие = Anticipation talent in Protection

**Comment by getov** [comment]
Thanks. Well, it looks like it works. What exactly is broken in your case?

**Comment by Ardash** [comment]
I have 310(+83)/310 defense (skills tab)
I see Defense: 310 on main character tab.

There is two 'defense' in GetSkillLineInfo(i) list for warriors: first from class skill group, second from weapon skills.

**Comment by getov** [comment]
If you hover over the Defense: 310 stat, what does the tooltip say? is it not "310 (+83)" ?

**Comment by Ardash** [comment]
image

**Comment by getov** [comment]
Can you show me a screenshot from your skill groups tab ? If there are repeating skills for classes I will have to think of a more general solution.

**Comment by Ardash** [comment]
image

[image](https://user-images.githubusercontent.com/4602853/66437554-ad673f80-ea32-11e9-97a5-7e4c2acda417.png)

[image](https://user-images.githubusercontent.com/4602853/66437592-c839b400-ea32-11e9-976d-8a29815d9473.png)

[image](https://user-images.githubusercontent.com/4602853/66437636-f15a4480-ea32-11e9-827b-083e0c9e45d6.png)

**Comment by getov** [comment]
I think I know what's the problem now, and it happens to be only for the russian clients, because the word for "Protection" spec = "Защита" and the word for the Defense stat is also "Защита" . Am I right ?

**Comment by getov** [comment]
The reason I am not accepting your fix is because it is not elegant on one hand and on the other hand the order of these skill line infos is not deterministic. It is different for every class and dependant on the current level of the character. Therefore you cannot assume that the first index will always be equal to "Defense".

**Comment by Ardash** [comment]
Yes, you're right. But Warrior's tree calls Defense. Protection is Paladin's tree.

**Comment by Ardash** [comment]
Yes, you're right

**Comment by getov** [comment]
In English, the Warrior's talent trees are Arms, Fury, Protection
You can use your fix for yourself atm. I will see if I can make a more general solution. 
Thanks for the feedback :)

**Comment by Ardash** [comment]
Thanks

**Pull request closed without merging**
